### PR TITLE
couple changes for ubuntu, couple bug fixes, various stuff

### PR DESCRIPTION
**Pull request by jfgibbins**
I've done a few changes, including but not limited to the following based on what I can remember.

Adding ubuntu to detection.
some changes in 512 as several were being hardcoded instead of using %I
changes to dns maintain distro for variables
I tried to keep everything modular so as not to break anything as you've done
found issues with apparmor, particularly with using a sub-dir for /run/named, changed to using %I.pid rather than subdir...

If you're interested take a look, correct my corrects and merge, or if you don't want to mess with yours, no worries, just let me know, and I'll just keep mine as a separate for.   Some very cool stuff in your work.  Given me a lot of ideas and some fun things to learn.  
Thank you,
James

### CODE REVIEW

**Comment by jfgibbins** [comment]
fyi...my first time doing a pull or anything like that, so no idea at all if anything is right, haha

**Comment by egberts** [comment]
Those are very nice addition.  Ive got yet another fresh install and will be testing eith this tonight.

**Comment by egberts** [comment]
Testing... the push.

**Comment by jfgibbins** [comment]
Cool.  I ended up forking to my local gitlab and started doing a complete refactor.  I started getting some ideas in my head and thought some if might just be to much change and break things for later stuff, so I've split it off.  But I will end up mirroring it back to github later.  Right now, I've got it where it builds a basic framework for a non-personalized server.  Aka, install, services, directory and file structure for named and named@.  Also did quite a few changes on RNDC, and went ahead and did what I thnk you were going to have a later script do, at least from your README, of combining all the keys and parameters for it in /etc/bind/rndc.conf.  Very much like you have, just with some more fixes, etc.  and for example, like moving systemd/system/named-???? to the setup so it runs every time you make a regular or named instance, and leaving system to just make the systemd files.  Right now, I'm working on where I think you left off with adding personality to a server, authoritative, recursive, caching, etc.  Looking forward to see some of what you've added.  I've defininately learned a lot on systemd, bind and bash that I didn't know before.  Very much appreciated.  FYI, I think I'll mirror what I have to GH in a few minutes here.

**Pull request closed without merging**
